version: '3'
services:
  lingua-mate-postgres:
    env_file: postgres.env
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  lingua-mate-keycloak:
    image: jboss/keycloak:16.1.1
    env_file: keycloak.env
    ports:
      - '8081:8080'
    depends_on:
      - lingua-mate-postgres

  lingua-mate-backend:
    env_file: backend.env
    image: linguamate/linguamate-backend:0.0.1-SNAPSHOT
    ports:
      - '8082:8080'
    depends_on:
      - lingua-mate-postgres
      - lingua-mate-keycloak

  # lingua-mate-web-frontend:
  #   image: nginx:alpine
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./path/to/angular/dist:/usr/share/nginx/html
  #   depends_on:
  #     - lingua-mate-backend

volumes:
  postgres_data:
